// src/pages/+Layout.tsx
import { Config } from "vike-react/Config";
import { ToastProvider } from "#/hooks/useToaster";
import { useTranslation } from "#/hooks/useTranslation";
import { Button } from "#/components/Button";

import "./index.css";

const SwitchLanguageButton = () => {
  const { t, language, changeLanguage } = useTranslation();

  return (
    <Button
      variant="subtle"
      onClick={() => changeLanguage(language === "en" ? "zh" : "en")}
    >
      {t("language")}
    </Button>
  );
};

export const Layout = ({ children }: { children: JSX.Element }) => {
  const { t } = useTranslation();

  return (
    <>
      <Config title={t("overtime_tracker")} />
      <ToastProvider>
        <>
          <div className="flex justify-end p-2">
            <SwitchLanguageButton />
          </div>
          {children}
        </>
      </ToastProvider>
    </>
  );
};

// src/routes/+layout.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { language, t, changeLanguage } from "#/stores/messages.svelte";
  import Button from "#/components/button.svelte";
  import Toasts from "#/components/toasts.svelte";
  import { request } from "#/utils/request";
  import "../app.css";

  const { children }: { children: Snippet } = $props();

  let isSwitchingLanguage = $state(false);

  const onSwitchLanguage = async () => {
    isSwitchingLanguage = true;
    try {
      const newLanguage = language() === "en" ? "zh" : "en";
      void request("/api/preferences/language", "PUT", { language: newLanguage });
      await changeLanguage(newLanguage);
    } finally {
      isSwitchingLanguage = false;
    }
  };
</script>

<svelte:head>
  <title>{t("overtime_tracker")}</title>
</svelte:head>

{#snippet switchLanguageButton()}
  <Button variant="subtle" onclick={onSwitchLanguage} loading={isSwitchingLanguage}>
    {t("language")}
  </Button>
{/snippet}

<div class="flex justify-end p-2">
  {@render switchLanguageButton()}
</div>
{@render children()}
<Toasts />
