// components/Modal.tsx
import React from "react";
import {
  Close,
  Content,
  Overlay,
  Portal,
  Root,
  Title,
} from "@radix-ui/react-dialog";

import "./Modal.css";

const CloseButton = () => {
  return (
    <Close className="absolute top-3.5 right-3.5 p-1 hover:bg-gray-100 rounded-full cursor-pointer">
      <svg
        className="w-5 h-5"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M6 18L18 6M6 6l12 12"
        />
      </svg>
    </Close>
  );
};

interface ModalProps {
  title: string;
  opened: boolean;
  onClose: () => void;
  children: React.ReactNode;
}

export const Modal = ({ title, opened, onClose, children }: ModalProps) => (
  <Root open={opened} onOpenChange={onClose}>
    <Portal>
      <Overlay className="modal-overlay fixed inset-0 bg-black/50" />
      <Content
        className="modal-content fixed left-[50%] top-[50%] translate-x-[-50%] translate-y-[-50%] w-full max-w-sm rounded-lg bg-white shadow-xl p-4"
        aria-describedby={undefined}
      >
        <Title className="text-lg font-medium mb-4">{title}</Title>
        {children}
        <CloseButton />
      </Content>
    </Portal>
  </Root>
);

// src/components/modal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { fade } from "svelte/transition";
  import { createDialog, melt } from "@melt-ui/svelte";

  interface ModalProps {
    open?: boolean;
    heading?: Snippet;
    children: Snippet;
  }

  let { open = $bindable(), heading, children }: ModalProps = $props();

  const {
    elements: { overlay, content, title, close, portalled },
    states: { open: stateOpen },
  } = createDialog({
    defaultOpen: open,
  });

  // Sync states
  $effect(() => {
    $stateOpen = open ?? false;
  });
  $effect(() => {
    open = $stateOpen;
  });
  const duration = 150;
</script>

{#if $stateOpen}
  <div use:melt={$portalled}>
    <div
      use:melt={$overlay}
      in:fade={{ duration }}
      out:fade={{ duration }}
      class="fixed inset-0 bg-black/50"
    ></div>
    <div
      use:melt={$content}
      in:fade={{ duration }}
      out:fade={{ duration }}
      class="fixed left-[50%] top-[50%] w-full max-w-sm translate-x-[-50%] translate-y-[-50%] rounded-lg bg-white p-4 shadow-xl"
    >
      {#if heading}
        <div use:melt={$title} class="mb-4 text-lg font-medium">{@render heading()}</div>
      {/if}
      {@render children()}
      {@render closeButton()}
    </div>
  </div>
{/if}

{#snippet closeButton()}
  <button
    use:melt={$close}
    aria-label="close"
    class="absolute right-3.5 top-3.5 cursor-pointer rounded-full p-1 hover:bg-gray-100"
  >
    <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M6 18L18 6M6 6l12 12"
      />
    </svg>
  </button>
{/snippet}
